---
title: "Content file"
output: html_document
date: '2023-08-04'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Something that could go into the readme file in the future, plots used in our poster is inside Archive named Plots_for_Poster.rmd

# Begin with looking at coreg_eda_1st.rmd : 
    co-registered file, 
    plots of coreg and before coreg plot
    hill shade plot 
    created stor_cor_df from the coreg raster file 
    Added stor_cor_glacier consists of our slope_degrees, eastness, northness, bin for slope, curvature(plan,prof,max),elevation,northness,eastness, and aspect. 
    used in z_score_3rd, variogram_rolstad_4th, 
    
    
# coregistered_interpolation_2nd.Rmd :
    Hypsometric interpolation method used to predict the void area
    Created 3 different polynomial regression models to predict the missing elev_diff_no_outliers
    Total volume change calculated
    Raster plot to look at the new filled in glacier
   
# z_score_3rd.rmd :
    Has two different datasets for the Median and NMAD models respectively
    Predicted the Median value using the Median model and the NMAD value using the piece wise model, which     is part of the detrending and standardization process
    Calculated the z-score using the formula (elev_diff_no_outliers - pred_med_elev_diff) / pred_mad
    Also has the Raster plot for the z-score
    

# Variogram Rolstad_4th 
    Uses stor_cor_na that is created from stor_cor_glacier to drop na values of z-score, takes population
    sample of 5000 to fit in a variogram model with z_score as response and no explanatory
    variables(intercept). 
  
# error_prop_5th.Rmd
    The file contains code for calculating the final uncertainty of the overall volume change based on         bins, which is the most accurate method, looking at the glacier as a whole without accounting for bins,     and not accounting for spatial correlation. In this case, we used the binned uncertainty value.

# kirg_6th 
    stor_void_zoomed created from stor_cor_glacier inorder to only look at the void area
    From stor_void_zoomed we created stor_void_na and stor.sf
    stor.sf drops na z_score values and is the data used to to model a variogram using z_score as response variable 
    stor_void_na filters na values that to help us predict
    Created predictions_z.csv after prediciton to join with stor_void_na to plot as a raster